export const seedTemplates = [
  {
    id: 'vehicle.sport-car',
    name: '未来跑车',
    category: 'vehicle',
    description: '低趴车身、宽轮距和发光装饰线，适合概念交通工具原型。',
    tags: ['车辆', '科幻', '概念'],
    defaultPrompt: '生成一辆未来感跑车，黑色车身，白色发光线条，低趴姿态。',
    complexity: 'medium',
  },
  {
    id: 'architecture.tower',
    name: '极简塔楼',
    category: 'architecture',
    description: '使用几何体堆叠形成的黑白建筑体块，适合空间概念验证。',
    tags: ['建筑', '城市', '体块'],
    defaultPrompt: '生成一座黑白极简风格的未来塔楼，包含阶梯式体块和顶部平台。',
    complexity: 'medium',
  },
  {
    id: 'aircraft.drone',
    name: '四旋翼飞行器',
    category: 'aircraft',
    description: '清晰表达机身、旋翼、支架和传感器结构。',
    tags: ['飞行器', '无人机', '工业'],
    defaultPrompt: '生成一个黑白工业风四旋翼无人机，带有中心传感器和细长支架。',
    complexity: 'medium',
  },
  {
    id: 'furniture.chair',
    name: '模块座椅',
    category: 'furniture',
    description: '由基础几何组成的现代家具，适合产品造型探索。',
    tags: ['家具', '座椅', '产品'],
    defaultPrompt: '生成一把黑白模块化休闲座椅，宽大靠背和金属支脚。',
    complexity: 'low',
  },
  {
    id: 'prop.beacon',
    name: '科幻信标',
    category: 'prop',
    description: '用于游戏场景和空间道具的低中精度程序化资产。',
    tags: ['道具', '游戏', '信标'],
    defaultPrompt: '生成一个黑白科幻能量信标，底座厚重，中心有发光柱体。',
    complexity: 'low',
  },
  {
    id: 'watch.premium-chronograph',
    name: '高级机械腕表',
    category: 'watch',
    description: '包含表壳、表圈、表盘、指针、刻度和表带结构的商业级穿戴产品模型。',
    tags: ['手表', '穿戴', '产品'],
    defaultPrompt: '生成一块高级机械腕表，黑色表盘，银色表壳，分层表圈，精密刻度和金属表带。',
    complexity: 'high',
  },
  {
    id: 'jewelry.necklace',
    name: '高级项链首饰',
    category: 'jewelry',
    description: '用于项链、手链、吊坠、珠宝和首饰的开放式商业产品模型。',
    tags: ['项链', '手链', '首饰', '珠宝'],
    defaultPrompt: '生成一条高级珠宝首饰，包含链节、吊坠、宝石镶嵌和精密金属结构。',
    complexity: 'high',
  },
  {
    id: 'product.generic-device',
    name: '通用产品设备',
    category: 'product',
    description: '用于镜子、飞机、耳机、相机、鞋履、包袋、小家电、智能硬件等开放式产品建模的通用模板。',
    tags: ['产品', '镜子', '飞机', '硬件', '开放生成'],
    defaultPrompt: '生成一个商业级开放产品模型，包含主体外壳、分层面板、控制区域和制造细节。',
    complexity: 'high',
  },
];
